package musicPlayerDB.entity;
// Generated Oct 9, 2013 1:30:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Song generated by hbm2java
 */
public class Song  implements java.io.Serializable {


     private SongId id;

    public Song() {
    }

    public Song(SongId id) {
       this.id = id;
    }
   
    public SongId getId() {
        return this.id;
    }
    
    public void setId(SongId id) {
        this.id = id;
    }

    public void setTitle(String title) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setArtist(String artist) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public String getTitle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


